# Generated by Django 2.2.4 on 2021-05-09 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=70, verbose_name='Descripción')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('Cantidad_Clases', models.IntegerField(verbose_name='Cantidad de clases')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Cantidad de planes',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalizacion')),
                ('Tipo_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membresia.Planes')),
            ],
            options={
                'verbose_name': 'Cliente',
            },
        ),
    ]
