# Generated by Django 2.2.4 on 2021-05-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
