# Generated by Django 2.2.4 on 2021-05-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresia', '0002_cliente_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='last_name',
            field=models.CharField(default='pratto', max_length=60, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
    ]
