# Generated by Django 2.2.4 on 2021-05-29 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresia', '0003_auto_20210511_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='clases',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Clases disponibles'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio'),
        ),
    ]
