# Generated by Django 2.2.4 on 2021-08-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresia', '0004_auto_20210529_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-state', 'name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.PositiveIntegerField(default=41060109, verbose_name='DNI'),
            preserve_default=False,
        ),
    ]
